name: Android CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      JAVA_VERSION: 17

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: ${{ env.JAVA_VERSION }}

    - name: Cache Gradle dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Download dependencies
      run: ./gradlew build --no-daemon

    - name: Run lint
      run: ./gradlew lint --no-daemon

    - name: Run tests
      run: ./gradlew test --no-daemon

    - name: Assemble Debug APK
      run: ./gradlew assembleDebug --no-daemon

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: Debug-APK
        path: app/build/outputs/apk/debug/app-debug.apk

    - name: Upload to testapp.io
      env:
        TESTAPP_API_KEY: ${{ secrets.TESTAPP_API_KEY }}
      run: |
        curl -F "file=@app/build/outputs/apk/debug/app-debug.apk" \
             -F "token=${{ secrets.TESTAPP_API_KEY }}" \
             -F "release_notes=Automated upload from GitHub Actions" \
             https://api.testapp.io/api/upload
